//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoobarElfTest.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FoobarElfTest.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0028)http://localhost:8888/djben/ --&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;&quot;&gt;&lt;HTML&gt;&lt;HEAD&gt;&lt;META 
        ///content=&quot;IE=5.0000&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///&lt;TITLE&gt;Hello&lt;/TITLE&gt;
        ///&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;META name=&quot;GENERATOR&quot; content=&quot;MSHTML 11.00.9600.17107&quot;&gt;&lt;/HEAD&gt; 
        ///&lt;BODY&gt;			{&quot;title&quot;:&quot;爱久见人心&quot;, &quot;albumArtist&quot;:&quot;梁静茹&quot;,  &quot;trackArtist&quot;:&quot;?&quot;, 
        ///&quot;album&quot;:&quot;爱久见人心&quot;, &quot;CD&quot;:&quot; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Aijiu_playing {
            get {
                return ResourceManager.GetString("Aijiu_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0028)http://localhost:8888/djben/ --&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;&quot;&gt;&lt;HTML&gt;&lt;HEAD&gt;&lt;META 
        ///content=&quot;IE=5.0000&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///&lt;TITLE&gt;Hello&lt;/TITLE&gt;
        ///&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;META name=&quot;GENERATOR&quot; content=&quot;MSHTML 11.00.9600.17107&quot;&gt;&lt;/HEAD&gt; 
        ///&lt;BODY&gt;			{&quot;title&quot;:&quot;屬於&quot;, &quot;albumArtist&quot;:&quot;梁静茹&quot;,  &quot;trackArtist&quot;:&quot;?&quot;, &quot;album&quot;:&quot;幸福的抉择  
        ///I Do&quot;, &quot;CD [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Shuyu_playing {
            get {
                return ResourceManager.GetString("Shuyu_playing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0028)http://localhost:8888/djben/ --&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;&quot;&gt;&lt;HTML&gt;&lt;HEAD&gt;&lt;META 
        ///content=&quot;IE=5.0000&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///&lt;TITLE&gt;Hello&lt;/TITLE&gt;
        ///&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;META name=&quot;GENERATOR&quot; content=&quot;MSHTML 11.00.9600.17107&quot;&gt;&lt;/HEAD&gt; 
        ///&lt;BODY&gt;&lt;BR&gt;		[{&quot;title&quot;:&quot;My Love (Radio Edit)&quot;, &quot;albumArtist&quot;:&quot;Westlife&quot;,  
        ///&quot;trackArtist&quot;:&quot;?&quot;, [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Stopped {
            get {
                return ResourceManager.GetString("Stopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;!-- saved from url=(0028)http://localhost:8888/djben/ --&gt;
        ///&lt;!DOCTYPE html PUBLIC &quot;-//W3C//DTD HTML 4.01 Transitional//EN&quot; &quot;&quot;&gt;&lt;HTML&gt;&lt;HEAD&gt;&lt;META 
        ///content=&quot;IE=5.0000&quot; http-equiv=&quot;X-UA-Compatible&quot;&gt;
        ///&lt;TITLE&gt;Hello&lt;/TITLE&gt;
        ///&lt;META http-equiv=&quot;Content-Type&quot; content=&quot;text/html; charset=utf-8&quot;&gt;
        ///&lt;META name=&quot;GENERATOR&quot; content=&quot;MSHTML 11.00.9600.17107&quot;&gt;&lt;/HEAD&gt; 
        ///&lt;BODY&gt;			{&quot;title&quot;:&quot;My Love (Radio Edit)&quot;, &quot;albumArtist&quot;:&quot;Westlife&quot;,  
        ///&quot;trackArtist&quot;:&quot;?&quot;, &quot;al [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Westlife {
            get {
                return ResourceManager.GetString("Westlife", resourceCulture);
            }
        }
    }
}
